server {
    listen 443 ssl default_server;
    server_name 115.191.9.22;

    ssl_certificate /etc/nginx/cert/lanshot-ip.crt;
    ssl_certificate_key /etc/nginx/cert/lanshot-ip.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    include /etc/nginx/snippets/lanshot-locations.conf;

    location / {
        return 404;
    }
}
